### ISSUE TITLE
Declaration errors when searching using text/searchtext

### ISSUE THREAD

**Issue by ERTurner** [michitux/dokuwiki-plugin-text#6]
- Warning: Declaration of renderer_plugin_text::php($text) should be compatible with Doku_Renderer_xhtml::php($text, $wrapper = 'code') in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::html($text) should be compatible with Doku_Renderer_xhtml::html($text, $wrapper = 'code') in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::camelcaselink($link) should be compatible with Doku_Renderer_xhtml::camelcaselink($link, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::locallink($hash, $name = NULL) should be compatible with Doku_Renderer_xhtml::locallink($hash, $name = NULL, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::externallink($url, $name = NULL) should be compatible with Doku_Renderer_xhtml::externallink($url, $name = NULL, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::interwikilink($match, $name, $wikiName, $wikiUri) should be compatible with Doku_Renderer_xhtml::interwikilink($match, $name, $wikiName, $wikiUri, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::windowssharelink($url, $name = NULL) should be compatible with Doku_Renderer_xhtml::windowssharelink($url, $name = NULL, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::emaillink($address, $name = NULL) should be compatible with Doku_Renderer_xhtml::emaillink($address, $name = NULL, $returnonly = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::internalmedia($src, $title = NULL, $align = NULL, $width = NULL, $height = NULL, $cache = NULL, $linking = NULL) should be compatible with Doku_Renderer_xhtml::internalmedia($src, $title = NULL, $align = NULL, $width = NULL, $height = NULL, $cache = NULL, $linking = NULL, $return = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582
- Warning: Declaration of renderer_plugin_text::externalmedia($src, $title = NULL, $align = NULL, $width = NULL, $height = NULL, $cache = NULL, $linking = NULL) should be compatible with Doku_Renderer_xhtml::externalmedia($src, $title = NULL, $align = NULL, $width = NULL, $height = NULL, $cache = NULL, $linking = NULL, $return = false) in C:\xampp\htdocs\dokuwiki\lib\plugins\text\renderer.php on line 582

**Comment by michitux** [comment]
Can this be closed as #7 has been applied or are there any more fixes necessary?

**Comment by ERTurner** [comment]
I haven't noticed any other issues; thank you for merging #7 ! Yes, this can be closed.
